from typing import Any, TypeVar

T = TypeVar('T', bound=Argon2Hasher)

class Argon2Hasher:
    options: dict[str, Any]
    def __init__(self, options: dict[str, Any] =...) -> None: ...
    def set_options(self, options: dict[str, Any]) -> T: ...
    def make(self, string: str) -> str: ...
    def make_bytes(self, string: str) -> bytes: ...
    def check(self, plain_string: str, hashed_string: bytes | str) -> bool: ...
    def needs_rehash(self, hashed_string: str) -> bool: ...
