from typing import Any, Optional

class InputBag:
    query_string: dict[str, Any]
    post_data: dict[str, Any]
    environ: dict[str, Any]
    def __init__(self) -> None: ...
    def load(self, environ: dict[str, Any]) -> InputBag: ...
    def parse(self, environ: dict[str, Any]) -> None: ...
    def get(self, name: str, default: Optional[Any] = ..., clean: bool = ..., quote: bool = ...) -> Any: ...
    def has(self, *names: list[str]) -> bool: ...
    def all(self) -> dict[str, Any]: ...
    def all_as_values(self, internal_variables: bool = ...) -> dict[str, Any]: ...
    def only(self, *args: Any) -> dict[str, Any]: ...
    def query_parse(self, query_string: str) -> dict[str, Any]: ...
    def parse_dict(self, dictionary: dict[str, Any]) -> dict[str, Any]: ...
    def add_post(self, key: str, value: Any) -> Any: ...
