from ..foundation.Application import Application
from ..utils.structures import data
from dotty_dict import Dotty # type: ignore
from typing import Any, Optional

class Configuration:
    reserved_keys: list[str]
    application: Application
    def __init__(self, application: Application) -> None: ...
    def load(self) -> None: ...
    def merge_with(self, path: str, external_config: str | dict[str, Any]) -> None: ...
    def set(self, path: str, value: Any) -> None: ...
    def has(self, path: str) -> bool: ...
    def all(self) -> Dotty: ...
    def get(self, path: str, default: Optional[Any] = ...) -> Any: ...
