from ...facades import Gate
from typing import Any

class Authorizes:
    def can(self, permission: str, *args: Any) -> bool: ...
    def cannot(self, permission: str, *args: Any) -> bool: ...
    def can_any(self, permissions: list[str], *args: Any) -> bool: ...
