from typing import Any, Optional as OptionalType

class DefaultType:
    value: Any
    obj: object
    def __init__(self, value: Any, obj: object) -> None: ...
    def default(self) -> Any: ...
    def __getattr__(self, attr: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __eq__(self, other: Any) -> bool: ...

class Optional:
    obj: object
    default: OptionalType[Any]
    def __init__(self, obj: object, default: OptionalType[Any] = ...) -> None: ...
    def __getattr__(self, attr: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def instance(self) -> object: ...
