from ..configuration import config as config
from ..foundation.Application import Application
from ..utils.str import add_query_params as add_query_params
from typing import Any

class UrlsHelper:
    app: Application
    def __init__(self, app: Application) -> None: ...
    def url(self, path: str = ..., query_params: dict[str, Any] = ...) -> str: ...
    def asset(self, alias: str, filename: str) -> str: ...
    def route(self, name: str, params: dict[str, Any] = ..., absolute: bool = ..., query_params: dict[str, Any] = ...) -> str: ...
