from ..configuration import config as config
from .Mail import Mail as Mail
from _typeshed import Incomplete

class MockMail(Mail):
    count: int
    driver: Incomplete
    def __init__(self, application, *args, **kwargs) -> None: ...
    def reset(self) -> None: ...
    def send(self, driver: Incomplete | None = ...): ...
    def seeEmailBcc(self, bcc): ...
    def seeEmailCc(self, cc): ...
    def seeEmailContains(self, contents): ...
    def getHtmlContents(self, contents): ...
    def getTextContents(self, contents): ...
    def seeEmailCountEquals(self, count): ...
    def seeEmailDoesNotContain(self, contents): ...
    def seeEmailFrom(self, assertion): ...
    def seeEmailReplyTo(self, assertion): ...
    def seeEmailSubjectContains(self, assertion): ...
    def seeEmailSubjectDoesNotContain(self, assertion): ...
    def seeEmailSubjectEquals(self, assertion): ...
    def seeEmailTo(self, assertion): ...
    def seeEmailPriority(self, assertion): ...
    def seeEmailWasNotSent(self): ...
    def seeEmailWasSent(self): ...
    def seeDriverWas(self, name): ...
