from .str import as_filepath as as_filepath

def base_path(relative_path: str = ...) -> str: ...
def views_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def controllers_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def mailables_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def config_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def migrations_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def seeds_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def jobs_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def resources_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
def models_path(relative_path: str = ..., absolute: bool = ...) -> str: ...
