from dotty_dict import dotty, Dotty # type: ignore
from typing import Any, Optional

def load(path: str, object_name: str | None = ..., default: str | None = ..., raise_exception: bool = ...) -> Optional[Any]: ...
def data(dictionary: dict[str, Any] = ...) -> Dotty: ...
def data_get(dictionary: dict[str, Any], key: str, default: Optional[Any] = ...) -> Any: ...
def data_set(dictionary: dict[str, Any], key: str, value: Any, overwrite: bool = ...) -> dict[str, Any]: ...
