from .Application import Application

class Kernel:
    application: Application
    def __init__(self, app: Application) -> None: ...
    def register(self) -> None: ...
    def load_environment(self) -> None: ...
    def register_framework(self) -> None: ...
    def register_commands(self) -> None: ...
    def register_testing(self) -> None: ...
