from typing import KeysView, TypeVar, ValuesView
from masonite.presets import Preset

T = TypeVar('T', bound=PresetsCapsule)

class PresetsCapsule:
    presets: dict[str, Preset]
    def __init__(self) -> None: ...
    def add(self, preset: Preset) -> T: ...
    def get_presets(self) -> ValuesView[Preset]: ...
    def get_presets_keys(self) -> KeysView[str]: ...
    def run(self, key: str) -> None: ...
