from ...foundation import Application
from ..File import File
from ..FileStream import FileStream
from ..UploadedFile import UploadedFile
from typing import Any, Optional, TypeVar

Options = dict[str, Any]

T = TypeVar('T', bound=AmazonS3Driver)

class AmazonS3Driver:
    application: Application
    options: Options
    connection: Incomplete
    def __init__(self, application: Application) -> None: ...
    def set_options(self, options: Options) -> T: ...
    def get_connection(self): ...
    def get_bucket(self) -> str: ...
    def get_name(self, path: str, alias: str) -> str: ...
    def put(self, file_path: str, content: str) -> str: ...
    def put_file(self, file_path: str, content: UploadedFile, name: str | None = ...) -> str: ...
    def get(self, file_path: str) -> bytes | None: ...
    def missing_file_exceptions(self) -> tuple(Exception): ...
    def exists(self, file_path: str) -> bool: ...
    def missing(self, file_path: str) -> bool: ...
    def stream(self, file_path: str) -> FileStream: ...
    def copy(self, from_file_path: str, to_file_path: str) -> None: ...
    def move(self, from_file_path: str, to_file_path: str) -> None: ...
    def prepend(self, file_path: str, content: str) -> str: ...
    def append(self, file_path: str, content: str) -> None: ...
    def delete(self, file_path: str) -> None: ...
    def store(self, file: File, name: Optional[str] = ...) -> str: ...
    def make_file_path_if_not_exists(self, file_path: str) -> bool: ...
    def get_files(self, directory: Optional[str] = ...) -> list[File]: ...
