from ..utils.filesystem import get_extension as get_extension
from io import FileIO

class FileStream:
    stream: FileIO
    def __init__(self, stream: FileIO, name: str | None = ...) -> None: ...
    def path(self) -> str: ...
    def extension(self) -> str: ...
    def name(self) -> str: ...
