from ..utils.filesystem import get_extension as get_extension

class File:
    content: bytes
    filename: str | None
    def __init__(self, content: bytes, filename: str | None = ...) -> None: ...
    def path(self) -> None: ...
    def extension(self) -> str: ...
    def name(self) -> str | None: ...
    def stream(self) -> bytes: ...
    def hash_path_name(self) -> str: ...
    def hash_name(self) -> str: ...
