from ..utils.filesystem import get_extension as get_extension

class UploadedFile:
    filename: str
    content: str | bytes
    def __init__(self, filename: str, content: str | bytes) -> None: ...
    def extension(self) -> str: ...
    @property
    def name(self) -> str: ...
    def path_name(self) -> str: ...
    def hash_path_name(self) -> str: ...
    def stream(self) -> str | bytes: ...
    def hash_name(self) -> str: ...
    def get_content(self) -> str | bytes: ...
    @property
    def size(self) -> int: ...
