from io import FileIO
from masonite.foundation import Application
from ..Recipient import Recipient as Recipient
from typing import Any, TypeVar

T = TypeVar('T', bound=MailgunDriver)

class MailgunDriver:
    application: Application
    options: dict[str, Any]
    content_type: str | None
    def __init__(self, application: Application) -> None: ...
    def set_options(self, options: dict[str, Any]) -> T: ...
    def get_mime_message(self) -> dict[str, str]: ...
    def get_attachments(self) -> list[tuple[str, FileIO]]: ...
    def send(self) -> None: ...
