from ...foundation.Application import Application
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP, SMTP_SSL
from ..Recipient import Recipient as Recipient
from typing import Any, TypeVar

T = TypeVar('T', bound=SMTPDriver)

class SMTPDriver:
    application: Application
    options: dict[str, Any]
    def __init__(self, application: Application) -> None: ...
    def set_options(self, options: dict[str, Any]) -> T: ...
    def get_mime_message(self) -> MIMEMultipart: ...
    def make_connection(self) -> SMTP | SMTP_SSL: ...
    def send(self) -> None: ...
