from typing import TypeVar

T = TypeVar('T', bound=Limit)

class Limit:
    max_attempts: int
    delay: int
    key: str
    def __init__(self, max_attempts: int = ..., delay: int = ...) -> None: ...
    @classmethod
    def per_minute(cls, max_attempts: int, minutes: int = ...) -> Limit: ...
    @classmethod
    def per_hour(cls, max_attempts: int, hours: int = ...) -> Limit: ...
    @classmethod
    def per_day(cls, max_attempts: int, days: int = ...) -> Limit: ...
    @classmethod
    def from_str(cls, limit: str) -> Limit: ...
    @classmethod
    def unlimited(cls) -> Limit: ...
    def by(self, key: str) -> T: ...
    def is_unlimited(self) -> bool: ...
