from ..routes import Route as Route
from ..utils.str import random_string as random_string
from .controllers import AuthenticationController as AuthenticationController
from _typeshed import Incomplete

class Api:
    application: Incomplete
    def __init__(self, application, driver_config: Incomplete | None = ...) -> None: ...
    config: Incomplete
    def set_configuration(self, config): ...
    def generate_token(self): ...
    def get_token(self): ...
    def validate_token(self, token): ...
    def regenerate_token(self, token): ...
    def attempt_by_token(self, token): ...
    @classmethod
    def routes(cls, auth_route: str = ..., reauth_route: str = ...): ...
