from ...foundation.Application import Application
from typing import Any, TypeVar

Options = dict[str, Any]

T = TypeVar('T', bound=PusherDriver)

class PusherDriver:
    application: Application
    connection: Any
    options: Options
    def __init__(self, application: Application) -> None: ...
    def set_options(self, options: Options) -> T: ...
    def get_connection(self) -> Any: ...
    def channel(self, channel: str, event: str, value: Any) -> None: ...
    def authorize(self, channel: str, socket_id: str | int) -> bool: ...
