from typing import Optional

class Sign:
    key: str
    encryption: Optional[bytes]
    def __init__(self, key: Optional[str] = ...) -> None: ...
    def sign(self, value: str) -> str: ...
    def unsign(self, value: Optional[str] = ...) -> str: ...
