from ..exceptions.exceptions import AuthorizationException as AuthorizationException

class AuthorizationResponse:
    status: int | None
    def __init__(self, allowed: bool, message: str = ..., status: int | None = ...) -> None: ...
    @classmethod
    def allow(cls, message: str = ..., status: int | None = ...) -> AuthorizationResponse: ...
    @classmethod
    def deny(cls, message: str = ..., status: int | None = ...) -> AuthorizationResponse: ...
    def allowed(self) -> bool: ...
    def authorize(self) -> AuthorizationResponse: ...
    def get_response(self) -> tuple[str, int | None]: ...
    def message(self) -> str: ...
