from ..foundation.Application import Application
from .Provider import Provider as Provider

class ExceptionProvider(Provider):
    application: Application
    def __init__(self, application: Application) -> None: ...
    def register(self) -> None: ...
    def boot(self) -> None: ...
