from ..foundation.Application import Application

class QueueProvider:
    application: Application
    def __init__(self, application: Application) -> None: ...
    def register(self) -> None: ...
    def boot(self) -> None: ...
