from ..foundation.Application import Application
from .Provider import Provider

class ViewProvider(Provider):
    application: Application
    def __init__(self, app: Application) -> None: ...
    def register(self) -> None: ...
    def boot(self) -> None: ...
