from .PublishableResource import PublishableResource as PublishableResource
from _typeshed import Incomplete

class Package:
    abs_root: str
    module_root: str
    name: str
    config: str
    commands: Incomplete
    views: Incomplete
    migrations: Incomplete
    controller_locations: Incomplete
    routes: Incomplete
    assets: Incomplete
    resources: Incomplete
    def __init__(self) -> None: ...
    def add_config(self, config_path): ...
    def add_views(self, location): ...
    def add_migrations(self, *migrations): ...
    def add_routes(self, *routes): ...
    def add_assets(self, *assets): ...
    def add_controller_locations(self, *controller_locations): ...
    def add_publishable_resource(self, key, source, abs_destination) -> None: ...
