from ..facades import Api as Api
from _typeshed import Incomplete

class JWTGuard:
    application: Incomplete
    connection: Incomplete
    def __init__(self, application) -> None: ...
    options: Incomplete
    def set_options(self, options): ...
    def attempt(self, username, password): ...
    def get_auth_column(self, username): ...
    def register(self, dictionary): ...
    def user(self): ...
    def attempt_by_id(self, user_id): ...
    def once(self): ...
