from ..foundation.Application import Application
from ..utils.filesystem import get_module_dir as get_module_dir
from ..utils.location import controllers_path as controllers_path, mailables_path as mailables_path, views_path as views_path
from .Command import Command as Command

class AuthCommand(Command):
    app: Application
    def __init__(self, application: Application) -> None: ...
    def handle(self) -> None: ...
    def get_template_path(self) -> str: ...
    def get_controllers_path(self) -> str: ...
    def mailables_path(self) -> str: ...
