from ..utils.console import AddCommandColors as AddCommandColors
from cleo import Application as CommandApplication # type: ignore
from cleo.io.io import IO # type: ignore
from typing import Optional, Protocol

class BaseCommand(Protocol):
    def __init__(self) -> None: ...
    def ignore_validation_errors(self) -> None: ...
    def set_application(self, application: Optional[CommandApplication] = ...) -> None: ...
    def configure(self) -> None: ...
    def execute(self, io: IO) -> int: ...
    def initialize(self, io: IO) -> None: ...
    def run(self, io: IO) -> int: ...
    def merge_application_definition(self, merge_args: bool = ...) -> None: ...
    def synopsis(self, short: bool = ...) -> str: ...

class Command(BaseCommand, AddCommandColors): ...
