from ..foundation.Application import Application
from ..utils.filesystem import get_module_dir as get_module_dir, make_directory as make_directory, render_stub_file as render_stub_file
from ..utils.location import jobs_path as jobs_path
from .Command import Command as Command

class MakeJobCommand(Command):
    app: Application
    def __init__(self, application: Application) -> None: ...
    def handle(self) -> int | None: ...
    def get_template_path(self) -> str: ...
    def get_jobs_path(self) -> str: ...
