from ..foundation.Application import Application
from ..utils.filesystem import make_directory as make_directory
from .Command import Command as Command

class MakePolicyCommand(Command):
    app: Application
    def __init__(self, application: Application) -> None: ...
    def handle(self) -> int | None: ...
    def get_template_path(self) -> str: ...
    def get_base_policy_path(self) -> str: ...
    def get_model_policy_path(self) -> str: ...
