from ..foundation.Application import Application
from ..utils.filesystem import get_module_dir as get_module_dir, render_stub_file as render_stub_file
from ..utils.location import controllers_path as controllers_path
from .Command import Command as Command

class MakeControllerCommand(Command):
    app: Application
    def __init__(self, application: Application) -> None: ...
    def handle(self) -> int | None: ...
    def get_basic_controller_path(self) -> str: ...
    def get_resource_controller_path(self) -> str: ...
    def get_api_controller_path(self) -> str: ...
