from .. import Middleware as Middleware
from ...facades import Request as Request, Response as Response, Session as Session
from typing import Any

class SessionMiddleware(Middleware):
    def before(self, request: Request, response: Response) -> Request: ...
    def after(self, request: Request, _: Any) -> Request: ...
    def with_input(self) -> Response: ...
    def with_errors(self, errors: list[str] | dict[str, Any]) -> Response: ...
    def with_success(self, success: list[str] | dict[str, Any]) -> Response: ...
