from .. import Middleware as Middleware
from ...request.request import Request
from ...response.response import Response

class VerifyCsrfToken(Middleware):
    exempt: list[str]
    def before(self, request: Request, response: Response) -> Request: ...
    def after(self, request: Request, response: Response) -> Request: ...
    def create_token(self, request: Request, response: Response) -> None: ...
    def verify_token(self, request: Request, token: str) -> bool: ...
    def in_exempt(self, request: Request) -> bool: ...
    def get_token(self, request: Request) -> str: ...
