from _typeshed import Incomplete
from masoniteorm.models import Model

class DatabaseNotification(Model):
    __fillable__: Incomplete
    __table__: str
    def notifiable(self) -> None: ...
    read_at: Incomplete
    def mark_as_read(self): ...
    def mark_as_unread(self): ...
    @property
    def is_read(self): ...
    @property
    def is_unread(self): ...
