class Notification:
    def via(self, notifiable) -> None: ...
    def should_send(self): ...
    def ignore_errors(self): ...
    def broadcast_on(self): ...
    @classmethod
    def type(cls): ...
    def dry(self): ...
    def fail_silently(self): ...
