from ..exceptions.exceptions import NotificationException as NotificationException
from .DatabaseNotification import DatabaseNotification as DatabaseNotification

class Notifiable:
    def notify(self, notification, drivers=..., dry: bool = ..., fail_silently: bool = ...): ...
    def route_notification_for(self, driver): ...
    def notifications(self): ...
    @property
    def unread_notifications(self): ...
    @property
    def read_notifications(self): ...
