class Sms:
    def __init__(self, text: str = ...) -> None: ...
    def from_(self, number): ...
    def text(self, text): ...
    def to(self, to): ...
    def set_unicode(self): ...
    def client_ref(self, client_ref): ...
    def build(self, *args, **kwargs): ...
    def get_options(self): ...
